name: 'Attempt build'
description: 'Attempts to build lots of different languages.'
runs:
  using: "composite"
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '.ruby-version'
    
    - uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
    
    - run: ${{ github.action_path }}/run_builds.sh
      shell: bash